added tests for simulate_solana
neonlabsorg/neon-tests pull request #467
Opened 2024-12-28 01:08 UTC by IvanAdamovNeon

2025-01-29 11:15 UTC, kristinaNikolaevaa requested changes

2025-01-29 11:15 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +                    index=index,
I merged PR where index was removed

2025-01-29 11:15 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +            if not done_execution:
You have a lot of the same code in each test
If it is possible please move something in functions (for example this check)

2025-01-29 11:15 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
all of your transactions are very simple 
lets's add  or replace couple of tests with iterative transactions to transactions with bigger amount of steps 
for example deploying erc20forSpl (look on erc20_for_spl_factory_contract  fixture and test test_next_operator_can_continue_trx_with_created_spl) 
or  update_storage(uint resize)

2025-02-06 00:24 UTC, IvanAdamovNeon commented on integration/tests/neon_evm/test_simulate_solana.py
> +    def test_simulate_solana_iterative_from_instruction(
@kristinaNikolaevaa

2025-02-07 12:42 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +            data=contract_code + b"".hex(),
why do you need b"".hex() ?

2025-02-07 12:42 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +    def test_simulate_solana_iterative_from_holder_account(
now you have 2 test with contract deploying 
this one and below
and this one deployng factory,  not the erc20 contract 
how many iteration it takes ? I mentioned the fixture with this contract as a way to deploy erc20 contract and use it as all instranctions with erc20 contract are heavy and contains a lot of iterations and we need at least 1 tests like this, with big number of iterations

2025-02-07 12:42 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +                index=index,
why do you need this index parameter? and condition index <= 500?

2025-02-07 12:42 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +    def _simulate_and_execute_tx(
please add allure.step

2025-02-07 12:42 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +# from conftest import EnvironmentConfig
not removed

2025-02-07 12:42 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +                blockhash=os.urandom(32).hex(),
how this parameter affect to response? maybe better to use real current blockhash?

2025-02-11 17:28 UTC, IvanAdamovNeon commented on integration/tests/neon_evm/test_simulate_solana.py
> +            data=contract_code + b"".hex(),
removed

2025-02-11 17:38 UTC, IvanAdamovNeon commented on integration/tests/neon_evm/test_simulate_solana.py
> +    def test_simulate_solana_iterative_from_holder_account(
the other test was testing deployment teansactions, but now that we have this one - it's redundant indeed, removed it
this deployment takes 4 transactions

2025-02-11 17:44 UTC, IvanAdamovNeon commented on integration/tests/neon_evm/test_simulate_solana.py
> +                index=index,
> why do you need this index paramete
it's used for assertion logs only

> condition index <= 500?
confused step and opcode per step count, removed

2025-02-12 22:15 UTC, IvanAdamovNeon commented on integration/tests/neon_evm/test_simulate_solana.py
> +                blockhash=os.urandom(32).hex(),
this parameter is only validated for its type but not used in the backend but I refactored to the latest blockhash

2025-02-13 13:39 UTC, kristinaNikolaevaa requested changes

2025-02-13 13:39 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +                index=index,
you can move index = 0 to _simulate_and_execute_tx at least
why do you need it as an argument of function

2025-02-13 13:39 UTC, kristinaNikolaevaa commented on integration/tests/neon_evm/test_simulate_solana.py
> +    def test_simulate_solana_iterative_from_holder_account(
can we make a test with big amount of iterative transactions? as I understand now the biggest number is 4

Yes, 1 test with deployment transaction is enough

2025-02-17 11:31 UTC, kristinaNikolaevaa approved these changes

2025-02-17 16:24 UTC, merged